TRUNCATE TABLE T_DET_ROLTERCEROCERTIFICADO
GO
TRUNCATE TABLE T_DET_ROLTERCEROSSCRPCNDPS
GO
TRUNCATE TABLE dbo.T_DET_ROLTERCEROSSCRPCNENFRMDD
GO
DELETE FROM T_DET_ROLTERCEROSUSCRIPCION
GO 
DBCC CHECKIDENT(T_DET_ROLTERCEROSUSCRIPCION,RESEED,0)
GO
TRUNCATE TABLE T_DET_ROLTERCEROCOTIZACION
GO
TRUNCATE TABLE T_MOV_SUSCRIPCION
GO
DELETE FROM T_MAE_SUSCRIPCION
GO 
DBCC CHECKIDENT(T_MAE_SUSCRIPCION,RESEED,0)
GO
TRUNCATE TABLE T_DET_BITACORA_CUOTA
GO
TRUNCATE TABLE T_MAE_CUOTA
GO
TRUNCATE TABLE T_DET_BITACORA_CERTIFICADO
GO
TRUNCATE TABLE T_DET_DATOPARTICULARCERTIFICADO
GO
TRUNCATE TABLE T_DET_PLANCOTIZACION
GO
DELETE FROM T_MAE_CERTIFICADO
GO 
DBCC CHECKIDENT(T_MAE_CERTIFICADO,RESEED,0)
GO
DELETE FROM T_MAE_COTIZACION
GO 
DBCC CHECKIDENT(T_MAE_COTIZACION,RESEED,0)
GO
DELETE FROM T_DET_COMPONENTEPLANPOLIZA
GO 
DBCC CHECKIDENT(T_DET_COMPONENTEPLANPOLIZA,RESEED,0)
GO
DELETE FROM T_MAE_POLIZA
GO 
DBCC CHECKIDENT(T_MAE_POLIZA,RESEED,0)
GO
DELETE FROM T_MAE_TERCERO WHERE N_ID_TERCERO>1
GO 
DBCC CHECKIDENT(T_MAE_TERCERO,RESEED,1)
GO
TRUNCATE TABLE T_MAE_LOGACCESO
GO
TRUNCATE TABLE T_DET_LIQUIDACION_PLANES
GO
TRUNCATE TABLE T_DET_LIQUIDACION_POLIZAAGRUPADA
GO
TRUNCATE TABLE T_DET_SUSCRIPCION_RECHAZADA
GO
------------------------------------------------------------------------------------------
DELETE FROM T_MAE_USUARIO_CANAL_PTOVENTA WHERE N_ID_USUARIO >32
GO
DELETE FROM T_MAE_USUARIO_CIA_PRODUCTO_PLAN WHERE N_ID_USUARIO >32
GO
DELETE FROM T_DET_USUARIOCLAVE WHERE N_ID_USUARIO >32
GO
DELETE FROM T_DET_USUARIOPERFIL WHERE N_ID_USUARIO >32
GO
DBCC CHECKIDENT(T_DET_USUARIOPERFIL,RESEED,27)
GO
DELETE FROM T_DET_USUARIOOPCIONPERFIL WHERE N_ID_USUARIO >32
GO
DELETE FROM T_MAE_USUARIO WHERE N_ID_USUARIO>32
GO
DBCC CHECKIDENT(T_MAE_USUARIO,RESEED,32)
GO
DELETE FROM T_DET_PERSONA WHERE N_ID_PERSONA > 40
GO
DBCC CHECKIDENT(T_DET_PERSONA,RESEED,31)
GO
DELETE FROM T_MAE_PERSONA WHERE N_ID_PERSONA > 40
GO
DBCC CHECKIDENT(T_MAE_PERSONA,RESEED,40)
GO
truncate table T_TEMP_USUARIOMAPFRE

--limpiamos tabla de personas