select * from T_MAE_CERTIFICADO order by 1 desc 
select TOP 100 * from T_MAE_SUSCRIPCION order by 1 desc 
select TOP 100 * from T_DET_ROLTERCEROSUSCRIPCION order by 1 desc  


select * from T_MAE_SUSCRIPCION WHERE N_ID_SUSCRIPCION=5116038
SELECT TOP 6000 * FROM T_DET_ROLTERCEROSUSCRIPCION WHERE N_ID_TIPOASEGURADO IN (640,641) AND N_ID_RESULTADOSA IS NOT NULL 




--5268043
SELECT COUNT(*)

--UPDATE  TOP (10000) ROLSUS
--SET 
--N_ID_RESULTADOSA= SUS.N_ID_RESULTADOSA
FROM T_MAE_SUSCRIPCION SUS WITH(NOLOCK) 
INNER JOIN T_DET_ROLTERCEROSUSCRIPCION ROLSUS ON SUS.N_ID_SUSCRIPCION=ROLSUS.N_ID_SUSCRIPCION 
WHERE ROLSUS.N_ID_TIPOASEGURADO IN (640,641)
AND ROLSUS.N_ID_RESULTADOSA IS NULL 


--N_ID_RESULTADOSA
--6

--SPS_T_PlanCotizaSeguroVidaGrupoParticular
--SPS_T_MaeEvaluacionDPSVidaPiuraValidarSuscripcion
--SPS_T_DetCtrlTecnicoValidarVidaGrupoParticular